remote_theme: pmarsceill/just-the-docs
search_enabled: true
last_edit_timestamp: true

title: Learning Notes
description: Notes on books, articles, talks that I find useful

plugins:
  - jekyll-seo-tag
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false

aux_links:
  "Learning Notes on GitHub":
    - "https://github.com/jamesgawn/learning"