remote_theme: pmarsceill/just-the-docs
search_enabled: true
gh_edit_repository: https://github.com/jamesgawn/learning
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
last_edit_timestamp: true